from django.urls import path
from account.views import (login, home, add_product, product_setting, add_all,  change_product, obyekt_by_agent,
delete_product, pechat_qilish, export_excel, get_kamera_ip, video_feed, suggest_mashina, guruhlar_list, 
add_xojayin, guruh_mashina_qoshish, kassa_login, kirim_hisobot, add_kirim, change_k_o_kelgani, suggest_common,
xaridordan_kirim_hisobot, sklad_products_list, add_sklad_products, add_yetkazib_beruvchi, add_retsept, sklad_hisobot,
retsept_list, haydovchi_chiqim, change_haydovchi_narx, add_haydovchi_narx, chiqim_hisobot, umumiy_chiqim, add_chiqim, 
ishchilar_davomati, add_ishchi, ishchilar_royxati, add_kelmagan_ishchilar, add_ortiqcha_xarajat, set_mijoz_narx, add_otkat, 
enter_mijoz_summa, maxsulot_tan_narx, toggle_selected, check_home, add_test_product, tashkilot_by_agent, get__zavod)

urlpatterns = [
    path('', login, name='login'),
    path('kirim/xaridor/', xaridordan_kirim_hisobot, name='xaridor_kirim'),
    path('add/xarajat/<int:zakaz_id>/', add_ortiqcha_xarajat, name='add_ortiqcha_xarajat'),
    path('home/', home, name='home'),
    path('add/', add_product, name='add_product'),
    path('test/', add_test_product, name='add_test_product'),
    path('setting/', product_setting, name='setting'),
    path('add/<int:add_id>/', add_all, name='add_all'),
    path('toggle-selected/<int:pk>/', toggle_selected, name='toggle_selected'),
    path('change/<int:pk>/', change_product, name='change_product'),
    path('delete/<int:pk>/', delete_product, name='delete_product'),
    path('pechat/<int:pk>/', pechat_qilish, name='pechat_qilish'),
    path('export-excel/', export_excel, name='export_excel'),
    path('get-kamera-ip/<int:kamera_id>/', get_kamera_ip, name='get_kamera_ip'),
    path('video_feed/<int:kamera_id>/', video_feed, name='video_feed'),
    path('suggest-mashina/', suggest_mashina, name='suggest_mashina'),
    path("guruhlar/", guruhlar_list, name="guruh_list"),
    path('add/egasi/', add_xojayin, name='add_xojayin'),
    path('guruh/<int:xojayin_id>/mashina-qoshish/', guruh_mashina_qoshish, name='mashina_qoshish'),
    path('kassa/login/', kassa_login, name='kassa_login'),
    path('kirim/hisob/', kirim_hisobot, name='kirim_hisobot'),
    path('kirim/add/', add_kirim, name='add_kirim'),
    path('change/jonatuvchi/<int:jonatuvchi_id>/', change_k_o_kelgani, name='change_jonatuvchi'),
    path('suggest/<str:model_name>/<str:field_name>/', suggest_common, name='suggest_common'),
    path('sklad/products/', sklad_products_list, name='sklad_products'),
    path('sklad/add/products/', add_sklad_products, name='add_sklad_products'),
    path('add/yetkazuvchi/', add_yetkazib_beruvchi, name='add_yetkazuvchi'),
    path('add/retsept/', add_retsept, name='add_retsept'),
    path('hisobot/sklad/', sklad_hisobot, name='sklad_hisobot'),
    path('retsept/list/', retsept_list, name='retsept_list'),
    path('chiqim/list/', haydovchi_chiqim, name='chiqim_list'),
    path('change/haydovchi/narx/<int:pk>/', change_haydovchi_narx, name='change_haydovchi_narx'),
    path('add/haydovchi/narx/<int:pk>/', add_haydovchi_narx, name='add_haydovchi_narx'),
    path('chiqim/hisobot/', chiqim_hisobot,  name='chiqim_hisobot'),
    path('umumiy/chiqim/', umumiy_chiqim, name='umumiy_chiqim'),
    path('add/chiqim/', add_chiqim, name='add_chiqim'),
    path('ishchilar/davomati/', ishchilar_davomati, name='ishchilar_davomati'),
    path('add/ishchi/', add_ishchi, name='add_ishchi'),
    path('ishchilar/royxati/', ishchilar_royxati, name='ishchilar_royxati'),
    path('add/kelmagan/ishchilar/', add_kelmagan_ishchilar, name='add_kelmagan_ishchi'),
    path('set/<int:zakaz_id>/summa/', set_mijoz_narx, name='set_xaridor_narx'),
    path('add/otkat/<int:zakaz_id>/', add_otkat, name='add_otkat'),
    path('enter/<int:zakaz_id>/money/', enter_mijoz_summa, name='enter_summa_mijoz'),
    path('maxsulot/<int:zakaz_id>/',  maxsulot_tan_narx, name='maxsulot_tan_narx'),
    path('check/home/', check_home, name='check_home'),
    path('ajax/tashkilot-by-agent/', tashkilot_by_agent, name='tashkilot_by_agent'),
    path('ajax/obyekt-by-agent/', obyekt_by_agent, name='obyekt_by_agent'),
    path('get/<int:xomashyo__id>/', get__zavod, name='get_zavod'),


]